services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: evently.api
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  evently.db:
    image: postgres:latest
    container_name: evently.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evently
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  evently.idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: evently.identity
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - "18080:8080"
  
  evently.seq:
    image: datalust/seq:latest
    container_name: evently.sequence
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8082:80"
  
  evently.cache:
    image: redis:latest
    container_name: evently.redis
    restart: always
    ports:
      - "6379:6379"